/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eclair;

import java.awt.Dimension;
import java.util.Random;
import javax.swing.JButton;

/**
 *
 * @author DEUVET
 */
public class jeu extends javax.swing.JFrame {
public int laposition=0;
    /**
     * Creates new form jeu
     */
    public jeu() {
        initComponents();
        affiche();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_reponse = new javax.swing.JTextArea();
        btn_go = new javax.swing.JButton();
        tf_rpj = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 791, Short.MAX_VALUE)
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        lbl_reponse.setEditable(false);
        lbl_reponse.setColumns(20);
        lbl_reponse.setLineWrap(true);
        lbl_reponse.setRows(5);
        jScrollPane1.setViewportView(lbl_reponse);

        btn_go.setText("GO");
        btn_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_go)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tf_rpj, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_rpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_go)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goActionPerformed
        // traitement du click sur le bouton go 
        
        String reponse;// declaration variable reponse
                    reponse = tf_rpj.getText();// recuperation du texte
                    reponse.toLowerCase();// mise en majuscule du texte
                    System.out.println("Le numero de la question est "+laposition);// affiche la triche dans le outpu pour debugger
                    
                    /*
                                    reste a faire
                    rendre inopérant le bouton qui vient d'etre clicqué
                    comparer la reponse utilisateur avec la reponse de la question variable laposition
                    scorer
                    englober cette procedure dans un controle pour NE calculer que si une valeur est mise dans le champ
                    */
    }//GEN-LAST:event_btn_goActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JButton btn_go;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lbl_reponse;
    private javax.swing.JTextField tf_rpj;
    // End of variables declaration//GEN-END:variables

    private void affiche() { // 
        int largeur = this.base.getWidth(); // extractions dimmensions du conteneur
        int hauteur = this.base.getHeight(); // extraction hauteur du conteneur (donc pannel)
        
        largeur = largeur / 3; // dimension d'une case de largeur = hauteur du tableau du pannel / 3
        hauteur= hauteur /3; // une case = hauteur du tableau du pannel / 3
        
        System.out.println("largeur"+largeur); // print = afficher, ici la largeur
        System.out.println("hauteur"+hauteur); // print = afficher, ici la hauteur
        monbouton [][] bouton = new monbouton[3][3]; // nouveau tableau de boutons
        
        for (int x = 0; x < 3; x++) // pour abissce jusqu'à 2 (< 3), ++ pour passer de l'une à l'autre
            for (int y = 0; y < 3; y++){ // pour ordonnée jusqu'à 2 (< 3), ++ pour passer de l'une à l'autre
            bouton [x] [y] = new monbouton(); // [x] (y] à chaque foi pour les 9 cases (abscisse ordonnée), les cases sont des boutons 
            bouton [x] [y].setPreferredSize(new Dimension (largeur, hauteur)); // 
            bouton [x] [y].setSize(new Dimension (largeur, hauteur)); //
            bouton [x] [y].setLocation (x*largeur,y*hauteur); //
            bouton [x] [y].setVisible(true); // rendre visible
            Random de = new Random(); // créer une variable de type aléatoire
            int position = de.nextInt(10);  // position = variable d'entier = nombre
            bouton[x] [y].setnumber(position);// affecte le numero de la question
            bouton[x] [y].setTexte_question(leclair.tableauquestionfacile[position][0]);
            
            bouton [x] [y].setText ("???"); // texte dans les cases
            bouton [x][y].addMouseListener(new java.awt.event.MouseAdapter(){
                @Override
                public void mouseReleased(java.awt.event.MouseEvent evt)
                {
                    
                    monbouton leboutonclique = (monbouton)evt.getSource(); // donner un nom aux boutons pour pouvoir les utiliser et leurs associer des actions dans le programme
                    laposition = leboutonclique.getnumber();
                    leboutonclique.affiche();
                    leboutonclique.setText(leclair.tableauquestionfacile[laposition][0]); // quand on clique sur un bouton celui ci affiche une questions aléatoires des questions faciles dans ce bouton
                    String Newligne=System.getProperty("line.separator"); 
                    String reponses = 1+" "+leclair.tableauquestionfacile[laposition][1]+Newligne+2+" "+leclair.tableauquestionfacile[laposition][2]+Newligne+3+" "+ leclair.tableauquestionfacile[laposition][3];
                    lbl_reponse.setText(reponses); // afficher les réponses qui correspondent à la question dans un label
                   
                   
                }
            });
            this.base.add(bouton[x][y]); // 
            this.base.setVisible(true); //
            this.base.repaint(); // obligatoire pour rendre visible
            }
    }
}